#!/usr/bin/env bash

for a in "$@"; do
    if [[ $1 == "--subj" ]]; then
        exec $SHELL
        sleep 1
    fi
done

openssl \
    req \
    -x509   \
    -newkey rsa:2048 \
    -nodes  \
    -days   365 \
    -sha256 \
    -subj   '/CN=localhost' \
    -keyout ./conf/certs/prv.pem \
    -out    ./conf/certs/pub.pem